sudo: false
dist: trusty
language: java
install:
  - mkdir -p ${HOME}
  - cd ${HOME}
  - wget https://download.java.net/java/GA/jdk12/GPL/openjdk-12_linux-x64_bin.tar.gz
  - tar -xzf openjdk-12_linux-x64_bin.tar.gz
  - export JAVA_HOME=${HOME}/jdk-12
  - export PATH=${JAVA_HOME}/bin:${PATH}
  - java -version
  - cd -
script:
  - ./gradlew clean check
